//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sort.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class RequestFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestFaultFaultCode faultCodeField;
        
        private string faultDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RequestFaultFaultCode faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string faultDetails {
            get {
                return this.faultDetailsField;
            }
            set {
                this.faultDetailsField = value;
                this.RaisePropertyChanged("faultDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public enum RequestFaultFaultCode {
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        NOT_AUTHORIZED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class BaseRequestStatusResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseRequestResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class RequestResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class BaseRequestResponseType : RequestResultType {
        
        private long requestIdField;
        
        private bool requestIdFieldSpecified;
        
        private RequestType requestTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestIdSpecified {
            get {
                return this.requestIdFieldSpecified;
            }
            set {
                this.requestIdFieldSpecified = value;
                this.RaisePropertyChanged("requestIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RequestType requestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("requestType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public enum RequestType {
        
        /// <remarks/>
        ACTIVATION,
        
        /// <remarks/>
        DEACTIVATION,
        
        /// <remarks/>
        ACTIVATE_DEVICE_TEST,
        
        /// <remarks/>
        CHANGE_VIN,
        
        /// <remarks/>
        CHANGE_SIM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class BaseVehicleAttributesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService", ConfigurationName="ServiceReference1.VehicleActivationPort")]
    public interface VehicleActivationPort {
        
        // CODEGEN: Контракт генерации сообщений с операцией getRequestStatusByRequestId не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sort.ServiceReference1.RequestFault), Action="", Name="requestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestStatusResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseVehicleAttributesType))]
        Sort.ServiceReference1.getRequestStatusByRequestIdResponse getRequestStatusByRequestId(Sort.ServiceReference1.getRequestStatusByRequestIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sort.ServiceReference1.getRequestStatusByRequestIdResponse> getRequestStatusByRequestIdAsync(Sort.ServiceReference1.getRequestStatusByRequestIdRequest request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getRequestStatusByIccid не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sort.ServiceReference1.RequestFault), Action="", Name="requestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestStatusResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseVehicleAttributesType))]
        Sort.ServiceReference1.getRequestStatusByIccidResponse getRequestStatusByIccid(Sort.ServiceReference1.getRequestStatusByIccidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sort.ServiceReference1.getRequestStatusByIccidResponse> getRequestStatusByIccidAsync(Sort.ServiceReference1.getRequestStatusByIccidRequest request);
        
        // CODEGEN: Контракт генерации сообщений с операцией deactivateVehicleByIccid не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sort.ServiceReference1.RequestFault), Action="", Name="requestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestStatusResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseVehicleAttributesType))]
        Sort.ServiceReference1.deactivateVehicleResponse deactivateVehicleByIccid(Sort.ServiceReference1.deactivateVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sort.ServiceReference1.deactivateVehicleResponse> deactivateVehicleByIccidAsync(Sort.ServiceReference1.deactivateVehicleRequest request);
        
        // CODEGEN: Контракт генерации сообщений с операцией deactivateVehicleByVin не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sort.ServiceReference1.RequestFault), Action="", Name="requestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestStatusResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseVehicleAttributesType))]
        Sort.ServiceReference1.deactivateVehicleResponse1 deactivateVehicleByVin(Sort.ServiceReference1.deactivateVehicleRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sort.ServiceReference1.deactivateVehicleResponse1> deactivateVehicleByVinAsync(Sort.ServiceReference1.deactivateVehicleRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией activateVehicle не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sort.ServiceReference1.RequestFault), Action="", Name="requestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestStatusResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseVehicleAttributesType))]
        Sort.ServiceReference1.activateVehicleResponse activateVehicle(Sort.ServiceReference1.activateVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sort.ServiceReference1.activateVehicleResponse> activateVehicleAsync(Sort.ServiceReference1.activateVehicleRequest request);
        
        // CODEGEN: Контракт генерации сообщений с операцией changeVehicleAttributes не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sort.ServiceReference1.RequestFault), Action="", Name="requestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestStatusResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseVehicleAttributesType))]
        Sort.ServiceReference1.changeVehicleAttributesResponse changeVehicleAttributes(Sort.ServiceReference1.changeVehicleAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sort.ServiceReference1.changeVehicleAttributesResponse> changeVehicleAttributesAsync(Sort.ServiceReference1.changeVehicleAttributesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class GetRequestStatusByRequestIdRequestTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class GetRequestStatusByRequestIdResponseTypeStatus : BaseRequestStatusResponseType {
        
        private long requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequestStatusByRequestIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRequestStatusByRequestIdRequest", Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("request", IsNullable=false)]
        public Sort.ServiceReference1.GetRequestStatusByRequestIdRequestTypeRequest[] getRequestStatusByRequestIdRequest1;
        
        public getRequestStatusByRequestIdRequest() {
        }
        
        public getRequestStatusByRequestIdRequest(Sort.ServiceReference1.GetRequestStatusByRequestIdRequestTypeRequest[] getRequestStatusByRequestIdRequest1) {
            this.getRequestStatusByRequestIdRequest1 = getRequestStatusByRequestIdRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequestStatusByRequestIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRequestStatusByRequestIdResponse", Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("status", IsNullable=false)]
        public Sort.ServiceReference1.GetRequestStatusByRequestIdResponseTypeStatus[] getRequestStatusByRequestIdResponse1;
        
        public getRequestStatusByRequestIdResponse() {
        }
        
        public getRequestStatusByRequestIdResponse(Sort.ServiceReference1.GetRequestStatusByRequestIdResponseTypeStatus[] getRequestStatusByRequestIdResponse1) {
            this.getRequestStatusByRequestIdResponse1 = getRequestStatusByRequestIdResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class GetRequestStatusByIccidRequestTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iccidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
                this.RaisePropertyChanged("iccid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class GetRequestStatusByIccidResponseTypeStatus : BaseRequestStatusResponseType {
        
        private string iccidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
                this.RaisePropertyChanged("iccid");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequestStatusByIccidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRequestStatusByIccidRequest", Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("request", IsNullable=false)]
        public Sort.ServiceReference1.GetRequestStatusByIccidRequestTypeRequest[] getRequestStatusByIccidRequest1;
        
        public getRequestStatusByIccidRequest() {
        }
        
        public getRequestStatusByIccidRequest(Sort.ServiceReference1.GetRequestStatusByIccidRequestTypeRequest[] getRequestStatusByIccidRequest1) {
            this.getRequestStatusByIccidRequest1 = getRequestStatusByIccidRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequestStatusByIccidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRequestStatusByIccidResponse", Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("status", IsNullable=false)]
        public Sort.ServiceReference1.GetRequestStatusByIccidResponseTypeStatus[] getRequestStatusByIccidResponse1;
        
        public getRequestStatusByIccidResponse() {
        }
        
        public getRequestStatusByIccidResponse(Sort.ServiceReference1.GetRequestStatusByIccidResponseTypeStatus[] getRequestStatusByIccidResponse1) {
            this.getRequestStatusByIccidResponse1 = getRequestStatusByIccidResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class DeactivateVehicleByIccidRequestTypeTerminal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iccidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
                this.RaisePropertyChanged("iccid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class DeactivateByIccidRequestResultTypeResult : BaseRequestResponseType {
        
        private string iccidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
                this.RaisePropertyChanged("iccid");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deactivateVehicleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("terminal", IsNullable=false)]
        public Sort.ServiceReference1.DeactivateVehicleByIccidRequestTypeTerminal[] deactivateVehicleByIccidRequest;
        
        public deactivateVehicleRequest() {
        }
        
        public deactivateVehicleRequest(Sort.ServiceReference1.DeactivateVehicleByIccidRequestTypeTerminal[] deactivateVehicleByIccidRequest) {
            this.deactivateVehicleByIccidRequest = deactivateVehicleByIccidRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deactivateVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public Sort.ServiceReference1.DeactivateByIccidRequestResultTypeResult[] deactivateVehicleByIccidResponse;
        
        public deactivateVehicleResponse() {
        }
        
        public deactivateVehicleResponse(Sort.ServiceReference1.DeactivateByIccidRequestResultTypeResult[] deactivateVehicleByIccidResponse) {
            this.deactivateVehicleByIccidResponse = deactivateVehicleByIccidResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class DeactivateVehicleByVinRequestTypeTerminal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class DeactivateByVinRequestResultTypeResult : BaseRequestResponseType {
        
        private string vinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deactivateVehicleRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("terminal", IsNullable=false)]
        public Sort.ServiceReference1.DeactivateVehicleByVinRequestTypeTerminal[] deactivateVehicleByVinRequest;
        
        public deactivateVehicleRequest1() {
        }
        
        public deactivateVehicleRequest1(Sort.ServiceReference1.DeactivateVehicleByVinRequestTypeTerminal[] deactivateVehicleByVinRequest) {
            this.deactivateVehicleByVinRequest = deactivateVehicleByVinRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deactivateVehicleResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public Sort.ServiceReference1.DeactivateByVinRequestResultTypeResult[] deactivateVehicleByVinResponse;
        
        public deactivateVehicleResponse1() {
        }
        
        public deactivateVehicleResponse1(Sort.ServiceReference1.DeactivateByVinRequestResultTypeResult[] deactivateVehicleByVinResponse) {
            this.deactivateVehicleByVinResponse = deactivateVehicleByVinResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class ActivateVehicleRequestTypeVehicle : BaseVehicleAttributesType {
        
        private string iccidField;
        
        private string brandField;
        
        private string modelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
                this.RaisePropertyChanged("iccid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class ActivateVehicleResponseTypeResult : BaseRequestResponseType {
        
        private string vinField;
        
        private string iccidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
                this.RaisePropertyChanged("iccid");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activateVehicleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="activateVehicleRequest", Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vehicle", IsNullable=false)]
        public Sort.ServiceReference1.ActivateVehicleRequestTypeVehicle[] activateVehicleRequest1;
        
        public activateVehicleRequest() {
        }
        
        public activateVehicleRequest(Sort.ServiceReference1.ActivateVehicleRequestTypeVehicle[] activateVehicleRequest1) {
            this.activateVehicleRequest1 = activateVehicleRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activateVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="activateVehicleResponse", Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public Sort.ServiceReference1.ActivateVehicleResponseTypeResult[] activateVehicleResponse1;
        
        public activateVehicleResponse() {
        }
        
        public activateVehicleResponse(Sort.ServiceReference1.ActivateVehicleResponseTypeResult[] activateVehicleResponse1) {
            this.activateVehicleResponse1 = activateVehicleResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class ChangeVehicleAttributesRequestTypeVehicle : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://era.glonass.ru/ext/eraRegistrationService")]
    public partial class ChangeVehicleAttributesResponseTypeResult : RequestResultType {
        
        private string vinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeVehicleAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeVehicleAttributesRequest", Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vehicle", IsNullable=false)]
        public Sort.ServiceReference1.ChangeVehicleAttributesRequestTypeVehicle[] changeVehicleAttributesRequest1;
        
        public changeVehicleAttributesRequest() {
        }
        
        public changeVehicleAttributesRequest(Sort.ServiceReference1.ChangeVehicleAttributesRequestTypeVehicle[] changeVehicleAttributesRequest1) {
            this.changeVehicleAttributesRequest1 = changeVehicleAttributesRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeVehicleAttributesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeVehicleAttributesResponse", Namespace="http://era.glonass.ru/ext/eraRegistrationService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public Sort.ServiceReference1.ChangeVehicleAttributesResponseTypeResult[] changeVehicleAttributesResponse1;
        
        public changeVehicleAttributesResponse() {
        }
        
        public changeVehicleAttributesResponse(Sort.ServiceReference1.ChangeVehicleAttributesResponseTypeResult[] changeVehicleAttributesResponse1) {
            this.changeVehicleAttributesResponse1 = changeVehicleAttributesResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehicleActivationPortChannel : Sort.ServiceReference1.VehicleActivationPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleActivationPortClient : System.ServiceModel.ClientBase<Sort.ServiceReference1.VehicleActivationPort>, Sort.ServiceReference1.VehicleActivationPort {
        
        public VehicleActivationPortClient() {
        }
        
        public VehicleActivationPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleActivationPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleActivationPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleActivationPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sort.ServiceReference1.getRequestStatusByRequestIdResponse Sort.ServiceReference1.VehicleActivationPort.getRequestStatusByRequestId(Sort.ServiceReference1.getRequestStatusByRequestIdRequest request) {
            return base.Channel.getRequestStatusByRequestId(request);
        }
        
        public Sort.ServiceReference1.GetRequestStatusByRequestIdResponseTypeStatus[] getRequestStatusByRequestId(Sort.ServiceReference1.GetRequestStatusByRequestIdRequestTypeRequest[] getRequestStatusByRequestIdRequest1) {
            Sort.ServiceReference1.getRequestStatusByRequestIdRequest inValue = new Sort.ServiceReference1.getRequestStatusByRequestIdRequest();
            inValue.getRequestStatusByRequestIdRequest1 = getRequestStatusByRequestIdRequest1;
            Sort.ServiceReference1.getRequestStatusByRequestIdResponse retVal = ((Sort.ServiceReference1.VehicleActivationPort)(this)).getRequestStatusByRequestId(inValue);
            return retVal.getRequestStatusByRequestIdResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sort.ServiceReference1.getRequestStatusByRequestIdResponse> Sort.ServiceReference1.VehicleActivationPort.getRequestStatusByRequestIdAsync(Sort.ServiceReference1.getRequestStatusByRequestIdRequest request) {
            return base.Channel.getRequestStatusByRequestIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sort.ServiceReference1.getRequestStatusByRequestIdResponse> getRequestStatusByRequestIdAsync(Sort.ServiceReference1.GetRequestStatusByRequestIdRequestTypeRequest[] getRequestStatusByRequestIdRequest1) {
            Sort.ServiceReference1.getRequestStatusByRequestIdRequest inValue = new Sort.ServiceReference1.getRequestStatusByRequestIdRequest();
            inValue.getRequestStatusByRequestIdRequest1 = getRequestStatusByRequestIdRequest1;
            return ((Sort.ServiceReference1.VehicleActivationPort)(this)).getRequestStatusByRequestIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sort.ServiceReference1.getRequestStatusByIccidResponse Sort.ServiceReference1.VehicleActivationPort.getRequestStatusByIccid(Sort.ServiceReference1.getRequestStatusByIccidRequest request) {
            return base.Channel.getRequestStatusByIccid(request);
        }
        
        public Sort.ServiceReference1.GetRequestStatusByIccidResponseTypeStatus[] getRequestStatusByIccid(Sort.ServiceReference1.GetRequestStatusByIccidRequestTypeRequest[] getRequestStatusByIccidRequest1) {
            Sort.ServiceReference1.getRequestStatusByIccidRequest inValue = new Sort.ServiceReference1.getRequestStatusByIccidRequest();
            inValue.getRequestStatusByIccidRequest1 = getRequestStatusByIccidRequest1;
            Sort.ServiceReference1.getRequestStatusByIccidResponse retVal = ((Sort.ServiceReference1.VehicleActivationPort)(this)).getRequestStatusByIccid(inValue);
            return retVal.getRequestStatusByIccidResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sort.ServiceReference1.getRequestStatusByIccidResponse> Sort.ServiceReference1.VehicleActivationPort.getRequestStatusByIccidAsync(Sort.ServiceReference1.getRequestStatusByIccidRequest request) {
            return base.Channel.getRequestStatusByIccidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sort.ServiceReference1.getRequestStatusByIccidResponse> getRequestStatusByIccidAsync(Sort.ServiceReference1.GetRequestStatusByIccidRequestTypeRequest[] getRequestStatusByIccidRequest1) {
            Sort.ServiceReference1.getRequestStatusByIccidRequest inValue = new Sort.ServiceReference1.getRequestStatusByIccidRequest();
            inValue.getRequestStatusByIccidRequest1 = getRequestStatusByIccidRequest1;
            return ((Sort.ServiceReference1.VehicleActivationPort)(this)).getRequestStatusByIccidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sort.ServiceReference1.deactivateVehicleResponse Sort.ServiceReference1.VehicleActivationPort.deactivateVehicleByIccid(Sort.ServiceReference1.deactivateVehicleRequest request) {
            return base.Channel.deactivateVehicleByIccid(request);
        }
        
        public Sort.ServiceReference1.DeactivateByIccidRequestResultTypeResult[] deactivateVehicleByIccid(Sort.ServiceReference1.DeactivateVehicleByIccidRequestTypeTerminal[] deactivateVehicleByIccidRequest) {
            Sort.ServiceReference1.deactivateVehicleRequest inValue = new Sort.ServiceReference1.deactivateVehicleRequest();
            inValue.deactivateVehicleByIccidRequest = deactivateVehicleByIccidRequest;
            Sort.ServiceReference1.deactivateVehicleResponse retVal = ((Sort.ServiceReference1.VehicleActivationPort)(this)).deactivateVehicleByIccid(inValue);
            return retVal.deactivateVehicleByIccidResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sort.ServiceReference1.deactivateVehicleResponse> Sort.ServiceReference1.VehicleActivationPort.deactivateVehicleByIccidAsync(Sort.ServiceReference1.deactivateVehicleRequest request) {
            return base.Channel.deactivateVehicleByIccidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sort.ServiceReference1.deactivateVehicleResponse> deactivateVehicleByIccidAsync(Sort.ServiceReference1.DeactivateVehicleByIccidRequestTypeTerminal[] deactivateVehicleByIccidRequest) {
            Sort.ServiceReference1.deactivateVehicleRequest inValue = new Sort.ServiceReference1.deactivateVehicleRequest();
            inValue.deactivateVehicleByIccidRequest = deactivateVehicleByIccidRequest;
            return ((Sort.ServiceReference1.VehicleActivationPort)(this)).deactivateVehicleByIccidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sort.ServiceReference1.deactivateVehicleResponse1 Sort.ServiceReference1.VehicleActivationPort.deactivateVehicleByVin(Sort.ServiceReference1.deactivateVehicleRequest1 request) {
            return base.Channel.deactivateVehicleByVin(request);
        }
        
        public Sort.ServiceReference1.DeactivateByVinRequestResultTypeResult[] deactivateVehicleByVin(Sort.ServiceReference1.DeactivateVehicleByVinRequestTypeTerminal[] deactivateVehicleByVinRequest) {
            Sort.ServiceReference1.deactivateVehicleRequest1 inValue = new Sort.ServiceReference1.deactivateVehicleRequest1();
            inValue.deactivateVehicleByVinRequest = deactivateVehicleByVinRequest;
            Sort.ServiceReference1.deactivateVehicleResponse1 retVal = ((Sort.ServiceReference1.VehicleActivationPort)(this)).deactivateVehicleByVin(inValue);
            return retVal.deactivateVehicleByVinResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sort.ServiceReference1.deactivateVehicleResponse1> Sort.ServiceReference1.VehicleActivationPort.deactivateVehicleByVinAsync(Sort.ServiceReference1.deactivateVehicleRequest1 request) {
            return base.Channel.deactivateVehicleByVinAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sort.ServiceReference1.deactivateVehicleResponse1> deactivateVehicleByVinAsync(Sort.ServiceReference1.DeactivateVehicleByVinRequestTypeTerminal[] deactivateVehicleByVinRequest) {
            Sort.ServiceReference1.deactivateVehicleRequest1 inValue = new Sort.ServiceReference1.deactivateVehicleRequest1();
            inValue.deactivateVehicleByVinRequest = deactivateVehicleByVinRequest;
            return ((Sort.ServiceReference1.VehicleActivationPort)(this)).deactivateVehicleByVinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sort.ServiceReference1.activateVehicleResponse Sort.ServiceReference1.VehicleActivationPort.activateVehicle(Sort.ServiceReference1.activateVehicleRequest request) {
            return base.Channel.activateVehicle(request);
        }
        
        public Sort.ServiceReference1.ActivateVehicleResponseTypeResult[] activateVehicle(Sort.ServiceReference1.ActivateVehicleRequestTypeVehicle[] activateVehicleRequest1) {
            Sort.ServiceReference1.activateVehicleRequest inValue = new Sort.ServiceReference1.activateVehicleRequest();
            inValue.activateVehicleRequest1 = activateVehicleRequest1;
            Sort.ServiceReference1.activateVehicleResponse retVal = ((Sort.ServiceReference1.VehicleActivationPort)(this)).activateVehicle(inValue);
            return retVal.activateVehicleResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sort.ServiceReference1.activateVehicleResponse> Sort.ServiceReference1.VehicleActivationPort.activateVehicleAsync(Sort.ServiceReference1.activateVehicleRequest request) {
            return base.Channel.activateVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sort.ServiceReference1.activateVehicleResponse> activateVehicleAsync(Sort.ServiceReference1.ActivateVehicleRequestTypeVehicle[] activateVehicleRequest1) {
            Sort.ServiceReference1.activateVehicleRequest inValue = new Sort.ServiceReference1.activateVehicleRequest();
            inValue.activateVehicleRequest1 = activateVehicleRequest1;
            return ((Sort.ServiceReference1.VehicleActivationPort)(this)).activateVehicleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sort.ServiceReference1.changeVehicleAttributesResponse Sort.ServiceReference1.VehicleActivationPort.changeVehicleAttributes(Sort.ServiceReference1.changeVehicleAttributesRequest request) {
            return base.Channel.changeVehicleAttributes(request);
        }
        
        public Sort.ServiceReference1.ChangeVehicleAttributesResponseTypeResult[] changeVehicleAttributes(Sort.ServiceReference1.ChangeVehicleAttributesRequestTypeVehicle[] changeVehicleAttributesRequest1) {
            Sort.ServiceReference1.changeVehicleAttributesRequest inValue = new Sort.ServiceReference1.changeVehicleAttributesRequest();
            inValue.changeVehicleAttributesRequest1 = changeVehicleAttributesRequest1;
            Sort.ServiceReference1.changeVehicleAttributesResponse retVal = ((Sort.ServiceReference1.VehicleActivationPort)(this)).changeVehicleAttributes(inValue);
            return retVal.changeVehicleAttributesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sort.ServiceReference1.changeVehicleAttributesResponse> Sort.ServiceReference1.VehicleActivationPort.changeVehicleAttributesAsync(Sort.ServiceReference1.changeVehicleAttributesRequest request) {
            return base.Channel.changeVehicleAttributesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sort.ServiceReference1.changeVehicleAttributesResponse> changeVehicleAttributesAsync(Sort.ServiceReference1.ChangeVehicleAttributesRequestTypeVehicle[] changeVehicleAttributesRequest1) {
            Sort.ServiceReference1.changeVehicleAttributesRequest inValue = new Sort.ServiceReference1.changeVehicleAttributesRequest();
            inValue.changeVehicleAttributesRequest1 = changeVehicleAttributesRequest1;
            return ((Sort.ServiceReference1.VehicleActivationPort)(this)).changeVehicleAttributesAsync(inValue);
        }
    }
}
